play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  pathPrefixes = ["/"]

  allowedOrigins = [
    "http://localhost:3000",
    "https://49ec-84-40-153-126.ngrok-free.app"
  ]

  allowedHttpMethods = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS"
  ]

  allowedHttpHeaders = [
    "Accept",
    "Content-Type",
    "Origin"
  ]
}

play.filters.hosts {
  allowed = [
    "localhost:9000",
    "127.0.0.1:9000",
    ".ngrok-free.app"
  ]
}